### ISSUE TITLE
Mesh Refinement Using blockMesh Gives Less Qualified Results 

### ISSUE THREAD

**Issue by hamidmoezzi1988** [MicroNanoFlows/OpenFOAM-2.4.0-MNF#14]
Hello,

I created a simple geometry with 40,000 cells using blockMesh. With this coarse mesh, and 2 millions particles, I got roughly good results. However, To replicate the exact results from the paper I am comparing with, I have to create a mesh with 4,000,000 cells.

Nevertheless, I tried to increase the number of cells from 40,000 to around 1,000,000 and the number of particles from 2 to 15 millions. This time my results are even less qualified than the coarse mesh with 40,000 cells! 
Should I have used snappyHexMesh for refining the mesh? (I am asking because I read something about using snappyHexMesh tool for refining the mesh in the paper dsmcFoam+: An OpenFOAM based direct simulation Monte Carlo solver) 

Worth to mention:
My simulation is 2D axisymmetric, and is running in parallel (dsmcInitialise is run in serial). 

Thank you 
Hamid

**Comment by craigwhite87** [comment]
Please the axisymmetric tutorial case for how to use this feature: https://github.com/MicroNanoFlows/OpenFOAM-2.4.0-MNF/blob/devel-craig/tutorials/discreteMethods/dsmcFoamPlus/axisymmetricBluntCylinder/README There will be no need to use snappyHexMesh here, that is for cases where there is not enough memory on a single node to generate the mesh required.
