### ISSUE TITLE
How to impose vacuum BCs 

### ISSUE THREAD

**Issue by hamidmoezzi1988** [MicroNanoFlows/OpenFOAM-2.4.0-MNF#15]
Hello all,

I was wondering how I can impose vacuum boundary condition. I tried to use 0 for the outlet pressure in dsmcLiouFangPressureOutletSpecifiedMolarFraction BC,  but it results in FPE error. I read a thesis that they had imposed a very low temperature at the boundary to simulate vacuum condition. 
My second question is that the pressure we specify as the outlet pressure is the absolute pressure? I mean, if I want my outlet pressure to be atmospheric, should I enter 101325 Pa as the outlet pressure in outlet BCs considered in dsmcFoamPlus?

Any clarification and help would be highly appreciated.

Thank you for your time.
Best regards.
Hamid

**Comment by craigwhite87** [comment]
For vacuum conditions, you can try simply setting the boundary as a deletion patch and having no entry under for it in the generalBoundaries subdict. This is how vacuum conditions are simulated in hypersonic simulations.

Yes, all pressures are absolute in the DSMC code, so for 1 atm, you can enter 101325 Pa.

**Comment by hamidmoezzi1988** [comment]
Thank you very much Dr. White for your clarification and support. Just one thing remains, Ma number in my simulation is in the range 2-4, which I think is slightly below the Ma range for hypersonic regime, can I still use deletion patch  and no entry in the generalBoundaries to account for the vacuum condition?

Regards,
Hamid
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
