### ISSUE TITLE
Dynamic load balance 

### ISSUE THREAD

**Issue by azacharos** [MicroNanoFlows/OpenFOAM-2.4.0-MNF#5]
During the process of the dynamic load balance, more specific by the end of the process, the routine try to execute the command rmTimeDirs from the bash and it cannot be found and the run stops.

**Comment by craigwhite87** [comment]
I have pushed the script to ~/OpenFOAM/OpenFOAM-2.4.0-MNF/bin . You can pull from the devel-craig branch. You might have to change the permissions and/or make it executable on your machine once it's been pulled down.

**Comment by skyer1900** [comment]
Sorry,I don't find the script. when I perform parallel calculations of dsmcFoamPlus with scotch decompose method. But I also encountered an error：
_**sh: 1: rmTimeDirs: not found**_

1. In decomposePar, I set method : scotch; 
2. In loadbalanceDir，
enableBalancing   	true;
maximumAllowableImbalance       0.05;
3. In balanceParDir
numberOfSubdomains 6;
method          scotch;
weightField     dsmcRhoN_mixture;

I also use the script in paper `dsmcFoam+: An OpenFOAM based direct simulation Monte Carlo solver`
If possible, please show more details about how to solve it and where is the file

**Comment by craigwhite87** [comment]
Are you pulling from the devel-craig branch? https://github.com/MicroNanoFlows/OpenFOAM-2.4.0-MNF/tree/devel-craig/bin
